package feature

import "strings"

// Type is the type of the feature
type Type string

// Equal checks if two types are equal
func (t Type) Equal(y Type) bool {
	return strings.ToLower(string(t)) == strings.ToLower(string(y))
}

// String returns the string representation of the feature
func (t Type) String() string {
	return string(t)
}

// All feature types
const (
	// HomeKit types

	AccessoryFlags                        Type = "accessoryFlags"
	AccessoryIdentifier                   Type = "accessoryIdentifier"
	Active                                Type = "active"
	AdministratorOnlyAccess               Type = "administratorOnlyAccess"
	AirParticulateDensity                 Type = "airParticulateDensity"
	AirParticulateSize                    Type = "airParticulateSize"
	AirQuality                            Type = "airQuality"
	AppMatchingIdentifier                 Type = "appMatchingIdentifier"
	AudioFeedback                         Type = "audioFeedback"
	BatteryLevel                          Type = "batteryLevel"
	Brightness                            Type = "brightness"
	CarbonDioxideDetected                 Type = "carbonDioxideDetected"
	CarbonDioxideLevel                    Type = "carbonDioxideLevel"
	CarbonDioxidePeakLevel                Type = "carbonDioxidePeakLevel"
	CarbonMonoxideDetected                Type = "carbonMonoxideDetected"
	CarbonMonoxideLevel                   Type = "carbonMonoxideLevel"
	CarbonMonoxidePeakLevel               Type = "carbonMonoxidePeakLevel"
	Category                              Type = "category"
	ChargingState                         Type = "chargingState"
	ColorTemperature                      Type = "colorTemperature"
	ConfigureBridgedAccessory             Type = "configureBridgedAccessory"
	ConfigureBridgedAccessoryStatus       Type = "configureBridgedAccessoryStatus"
	ContactSensorState                    Type = "contactSensorState"
	CoolingThresholdTemperature           Type = "coolingThresholdTemperature"
	CurrentAirPurifierState               Type = "currentAirPurifierState"
	CurrentAmbientLightLevel              Type = "currentAmbientLightLevel"
	CurrentDoorState                      Type = "currentDoorState"
	CurrentFanState                       Type = "currentFanState"
	CurrentHeaterCoolerState              Type = "currentHeaterCoolerState"
	CurrentHeatingCoolingState            Type = "currentHeatingCoolingState"
	CurrentHorizontalTiltAngle            Type = "currentHorizontalTiltAngle"
	CurrentHumidifierDehumidifierState    Type = "currentHumidifierDehumidifierState"
	CurrentPosition                       Type = "currentPosition"
	CurrentRelativeHumidity               Type = "currentRelativeHumidity"
	CurrentSlatState                      Type = "currentSlatState"
	CurrentTemperature                    Type = "currentTemperature"
	CurrentTiltAngle                      Type = "currentTiltAngle"
	CurrentTime                           Type = "currentTime"
	CurrentVerticalTiltAngle              Type = "currentVerticalTiltAngle"
	DayOfTheWeek                          Type = "dayOfTheWeek"
	DigitalZoom                           Type = "digitalZoom"
	DiscoverBridgedAccessories            Type = "discoverBridgedAccessories"
	DiscoveredBridgedAccessories          Type = "discoveredBridgedAccessories"
	FilterChangeIndication                Type = "filterChangeIndication"
	FilterLifeLevel                       Type = "filterLifeLevel"
	FirmwareRevision                      Type = "firmwareRevision"
	HardwareRevision                      Type = "hardwareRevision"
	HeatingThresholdTemperature           Type = "heatingThresholdTemperature"
	HoldPosition                          Type = "holdPosition"
	Hue                                   Type = "hue"
	Identify                              Type = "identify"
	ImageMirroring                        Type = "imageMirroring"
	ImageRotation                         Type = "imageRotation"
	InUse                                 Type = "inUse"
	IsConfigured                          Type = "isConfigured"
	LeakDetected                          Type = "leakDetected"
	LinkQuality                           Type = "linkQuality"
	LockControlPoint                      Type = "lockControlPoint"
	LockCurrentState                      Type = "lockCurrentState"
	LockLastKnownAction                   Type = "lockLastKnownAction"
	LockManagementAutoSecurityTimeout     Type = "lockManagementAutoSecurityTimeout"
	LockPhysicalControls                  Type = "lockPhysicalControls"
	LockTargetState                       Type = "lockTargetState"
	Logs                                  Type = "logs"
	Manufacturer                          Type = "manufacturer"
	Model                                 Type = "model"
	MotionDetected                        Type = "motionDetected"
	Mute                                  Type = "mute"
	Name                                  Type = "name"
	NightVision                           Type = "nightVision"
	NitrogenDioxideDensity                Type = "nitrogenDioxideDensity"
	ObstructionDetected                   Type = "obstructionDetected"
	OccupancyDetected                     Type = "occupancyDetected"
	On                                    Type = "on"
	OpticalZoom                           Type = "opticalZoom"
	OutletInUse                           Type = "outletInUse"
	OzoneDensity                          Type = "ozoneDensity"
	PairSetup                             Type = "pairSetup"
	PairVerify                            Type = "pairVerify"
	PairingFeatures                       Type = "pairingFeatures"
	PairingPairings                       Type = "pairingPairings"
	PM10Density                           Type = "pm10Density"
	PM2_5Density                          Type = "pm2_5Density"
	PositionState                         Type = "positionState"
	ProgrammableSwitchEvent               Type = "programmableSwitchEvent"
	ProgrammableSwitchOutputState         Type = "programmableSwitchOutputState"
	ProgramMode                           Type = "programMode"
	Reachable                             Type = "reachable"
	RelativeHumidityDehumidifierThreshold Type = "relativeHumidityDehumidifierThreshold"
	RelativeHumidityHumidifierThreshold   Type = "relativeHumidityHumidifierThreshold"
	RemainingDuration                     Type = "remainingDuration"
	ResetFilterIndication                 Type = "resetFilterIndication"
	RotationDirection                     Type = "rotationDirection"
	RotationSpeed                         Type = "rotationSpeed"
	Saturation                            Type = "saturation"
	SecuritySystemAlarmType               Type = "securitySystemAlarmType"
	SecuritySystemCurrentState            Type = "securitySystemCurrentState"
	SecuritySystemTargetState             Type = "securitySystemTargetState"
	SelectedRTPStreamConfiguration        Type = "selectedRTPStreamConfiguration"
	SelectedStreamConfiguration           Type = "selectedStreamConfiguration"
	SerialNumber                          Type = "serialNumber"
	ServiceLabelIndex                     Type = "serviceLabelIndex"
	ServiceLabelNamespace                 Type = "serviceLabelNamespace"
	SetDuration                           Type = "setDuration"
	SetupEndpoints                        Type = "setupEndpoints"
	SlatType                              Type = "slatType"
	SmokeDetected                         Type = "smokeDetected"
	SoftwareRevision                      Type = "softwareRevision"
	StatusActive                          Type = "statusActive"
	StatusFault                           Type = "statusFault"
	StatusJammed                          Type = "statusJammed"
	StatusLowBattery                      Type = "statusLowBattery"
	StatusTampered                        Type = "statusTampered"
	StreamingStatus                       Type = "streamingStatus"
	SulphurDioxideDensity                 Type = "sulphurDioxideDensity"
	SupportedAudioStreamConfiguration     Type = "supportedAudioStreamConfiguration"
	SupportedRTPConfiguration             Type = "supportedRTPConfiguration"
	SupportedVideoStreamConfiguration     Type = "supportedVideoStreamConfiguration"
	SwingMode                             Type = "swingMode"
	TargetAirPurifierState                Type = "targetAirPurifierState"
	TargetAirQuality                      Type = "targetAirQuality"
	TargetDoorState                       Type = "targetDoorState"
	TargetFanState                        Type = "targetFanState"
	TargetHeaterCoolerState               Type = "targetHeaterCoolerState"
	TargetHeatingCoolingState             Type = "targetHeatingCoolingState"
	TargetHorizontalTiltAngle             Type = "targetHorizontalTiltAngle"
	TargetHumidifierDehumidifierState     Type = "targetHumidifierDehumidifierState"
	TargetPosition                        Type = "targetPosition"
	TargetRelativeHumidity                Type = "targetRelativeHumidity"
	TargetSlatState                       Type = "targetSlatState"
	TargetTemperature                     Type = "targetTemperature"
	TargetTiltAngle                       Type = "targetTiltAngle"
	TargetVerticalTiltAngle               Type = "targetVerticalTiltAngle"
	TemperatureDisplayUnits               Type = "temperatureDisplayUnits"
	TimeUpdate                            Type = "timeUpdate"
	TunnelConnectionTimeout               Type = "tunnelConnectionTimeout"
	TunneledAccessoryAdvertising          Type = "tunneledAccessoryAdvertising"
	TunneledAccessoryConnected            Type = "tunneledAccessoryConnected"
	TunneledAccessoryStateNumber          Type = "tunneledAccessoryStateNumber"
	ValveType                             Type = "valveType"
	Version                               Type = "version"
	VOCDensity                            Type = "vocDensity"
	Volume                                Type = "volume"
	WaterLevel                            Type = "waterLevel"

	// Custom types

	CurrentPower   Type = "currentPower"
	CurrentVoltage Type = "currentVoltage"
	CurrentAmpere  Type = "currentAmpere"
	EnergyUsed     Type = "energyUsed"
)
