language: go
services:
  - docker
notifications:
  email: false
go:
  - 1.11.x
  - 1.12.x
  - master
matrix:
  fast_finish: true
  allow_failures:
    - go: master
env:
  - GO111MODULE=on
  - BIBLIOTEK_TEST_INTEGRATION=1
cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
before_install:
  - go mod download
install: go build ./...
script: go test -race -v -coverprofile=profile.cov $(go list ./...)
after_script:
  - go get github.com/mattn/goveralls
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci

