language: go
services:
  - docker
notifications:
  email: false
branches:
  only:
  - master
go:
  - 1.11.x
  - 1.12.x
  - master
matrix:
  fast_finish: true
  allow_failures:
    - go: master
env:
  global:
    - GO111MODULE=on
    - BIBLIOTEK_TEST_INTEGRATION=1
cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
before_install:
  - docker pull eclipse-mosquitto:1.6.2
  - docker run -d -p 127.0.0.1:1883:1883 eclipse-mosquitto:1.6.2
  - docker ps
  - go mod download
install: go build ./...
script: go test -race -v -coverprofile=profile.cov $(go list ./...)
after_script:
  - go get github.com/mattn/goveralls
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci

