language: go
sudo: false
notifications:
  email: false
go:
  - 1.11.x
  - 1.12.x
  - master
matrix:
  fast_finish: true
  allow_failures:
    - go: master
env:
  - GO111MODULE=on
install: go mod download
script: go test -race -v $(go list ./...)
