name: CI
on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
    branches:
      - master
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
    branches:
      - master

jobs:
  build_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2-beta
      with:
        go-version: '1.14'
    - name: Build
      run: |
        go build lib.hemtjan.st/...
    - name: Get an MQTT broker
      env:
        MOSQUITTO_VERSION: 1.6.9
      run: |
        docker pull eclipse-mosquitto:${MOSQUITTO_VERSION}
        docker run -d --name broker -p 127.0.0.1:1883:1883 eclipse-mosquitto:${MOSQUITTO_VERSION} -- mosquitto -v
        docker ps
    - name: Unit and integration tests
      env:
        BIBLIOTEK_TEST_INTEGRATION: 1
      run: |
        go test -v -race -coverprofile=coverage.txt -covermode=atomic lib.hemtjan.st/...
    - name: Get broker logs on failure
      if: failure()
      run:
        docker logs broker
    - name: Upload code coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.txt
